### ISSUE TITLE
Planetary impact simulation failing after random amount of time: "error: [05595.1] xmf.c:xmf_prepare_file():86: Unable to open temporary file"

### ISSUE THREAD

**Issue by mjr230600** [SWIFTSIM/SWIFT#35]
Dear SWIFT team,

I have been using your code (mainly version 0.9) now for the past 10 months or so now to run giant impact simulations at a range of resolutions (10^5–10^7 particles). I haven't really had any issues that we haven't been able to fix before, but recently my jobs have started failing after some random amount of time (anywhere from a few hours to a few days), with the error in the log file: "error: [05595.1] xmf.c:xmf_prepare_file():86: Unable to open temporary file". I am also getting this issue when now running with SWIFT version 1.0.0. 

We have yet to be able to resolve this issue and figure out what is going on, and it seems strange that this has only started happening fairly recently since I have had no issues running exactly the same types of jobs previously. For reference, I am also using WoMa/Seagen to build the planets/set-up the impacts etc. Any help or guidance would be very much appreciated!

Thanks very much once again. Best wishes,

Matt

**Comment by pwdraper** [comment]
Hi Matt, 
that report is a little misleading, it really means that the temporary file could not be created. So the usual reasons for that are trying to open the file when your quota is exceeded, the directory has been moved or deleted, the permissions have changed etc. 

One other possibility is a contention issue, that is the file is being used by more than one process. This could happen if you are running multiple jobs from the same directory, or you are running SWIFT using  mpirun/mpiexec but are running the non-MPI binary by mistake. This latter way is the only time I have seen this message.

Regards, Peter.

**Comment by MatthieuSchaller** [comment]
@mjr230600 did that work for you?

**Comment by MatthieuSchaller** [comment]
Glad it's all solved! :)
