### ISSUE TITLE
Swift webstorage is inaccessible

### ISSUE THREAD

**Issue by burgerz0** [SWIFTSIM/SWIFT#36]
When entering the site this error is given:

Error 403: Forbidden

You don't have permission to access /swift-webstorage on this server
![Screenshot 2023-08-05 120942](https://github.com/SWIFTSIM/SWIFT/assets/139862538/c9d22fb3-2297-450a-941c-9d267c3abb1c)

**Comment by pwdraper** [comment]
The backing store was down for maintenance. Should be working now.

**Comment by burgerz0** [comment]
Thank you.
