### ISSUE TITLE
SIDM Branch not compiling due to parallel issues

### ISSUE THREAD

**Issue by davidharvey1986** [SWIFTSIM/SWIFT#37]
When trying to compile the SIDM branch of Swift to a large machine it has issues with the parallel_io.c. I have attached the configuration of SWIFT and the error log
[configure.log](https://github.com/SWIFTSIM/SWIFT/files/12395417/configure.log)
 file.

[error.log](https://github.com/SWIFTSIM/SWIFT/files/12395403/error.log)

**Comment by davidharvey1986** [comment]
Hi there, so following this I have made some hacks at parallel_io.c and now it compiles (plus some extra indentation and print statement complaints), I haven't test this yet though. So let me know what you want me to do with this changes.

**Comment by MatthieuSchaller** [comment]
You can also run without parallel-hdf5 as a backup option?

**Comment by davidharvey1986** [comment]
I guess this only effects the writing the snap shots? And wont massively impact the speed?

**Comment by MatthieuSchaller** [comment]
Snapshots only, yes. Whether the parallel-io is faster than the distributed one is dependant on your file-system.

**Comment by davidharvey1986** [comment]
Well, its compiled and seems to be running, so I will pass these changes past Camila as they could be committed.
