### ISSUE TITLE
README.md link to onboarding guide is broken

### ISSUE THREAD

**Issue by apontzen** [SWIFTSIM/SWIFT#44]
The link is to `http://www.swiftsim.com/onboarding.pdf` but this redirects to `https://swift.strw.leidenuniv.nl/` instead of `https://swift.strw.leidenuniv.nl/onboarding.pdf`. Either the web server configuration needs correcting, or the link should be fixed.

**Comment by MatthieuSchaller** [comment]
Thanks, the web server was updated last week and broke all kinds of things.... I'll check this.

**Comment by MatthieuSchaller** [comment]
I have now fixed it. Thanks for reporting!
