### ISSUE TITLE
Issue Encountered Running autogen.sh Script in SWIFT-master Directory

### ISSUE THREAD

**Issue by JFBookwood** [SWIFTSIM/SWIFT#51]
Dear SWIFT Team,

I hope this message finds you well.

I'm writing to report an issue I encountered while setting up the SWIFT project on my Windows 11 system using Windows PowerShell.

**Issue Description:**
After downloading the SWIFT-master directory from GitHub and following the provided setup instructions, I faced difficulty executing the `autogen.sh` script in Windows PowerShell. Instead of running as expected, the script prompted me to select a program to open it with, rather than executing it as a shell script.

**Steps Taken:**
1. Downloaded SWIFT-master directory from GitHub.
2. Attempted to execute `autogen.sh` script in Windows PowerShell.
3. Encountered a prompt to choose a program to open the script with, rather than executing it.

**Expected Behavior:**
The `autogen.sh` script should execute as a shell script, generating the necessary files for configuring the SWIFT project.

**Observed Behavior:**
The script prompts the user to select a program to open it with, rather than executing.

**Efforts to Resolve:**
1. Tried granting executable permissions to the script using `chmod +x autogen.sh`, but the issue persisted.

**System Information:**
- Operating System: Windows 11
- Terminal: Windows PowerShell

I kindly request your assistance in resolving this issue and successfully configuring the SWIFT project on my Windows 11 system. Any guidance or support you can provide would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by MatthieuSchaller** [comment]
Hi! Thanks for your interest in the code.

Unfortunately, we do not support running on a native windows system. 
Using WSL might work as an alternative for installation on your machine. 

Hope this helps!

**Comment by JFBookwood** [comment]
Thanks
